In [74]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore', category=UserWarning)

# 1. Predict probabilities using your 4-feature array
probs = model.predict_proba(X_future_array)

# 2. Map percentages
schedule["Home Win %"] = (probs[:, 0] * 100).round(1)
schedule["Away Win %"] = (probs[:, 1] * 100).round(1)
schedule["Draw %"] = (probs[:, 2] * 100).round(1)

# 3. Create the clean output dataframe
prediction_output = schedule[["match_number", "Home Team", "Away Team", "Home Win %", "Away Win %", "Draw %"]]

# 4. Tell pandas to show ALL rows on screen
pd.set_option('display.max_rows', None) 
print(prediction_output)

# 5. Export ALL predictions to a clean CSV file inside your data folder
prediction_output.to_csv("data/predictions_2026_output.csv", index=False)
print("\n Done! All match predictions saved to 'data/predictions_2026_output.csv'")

    match_number               Home Team               Away Team  Home Win %  \
0        Match 1                  Mexico            South Africa        73.5
1        Match 2             South Korea          Czech Republic        55.4
2        Match 3                  Canada  Bosnia and Herzegovina        61.0
3        Match 4           United States                Paraguay        65.5
4        Match 5                   Haiti                Scotland        13.7
5        Match 6               Australia                  Kosovo        57.6
6        Match 7                  Brazil                 Morocco        57.2
7        Match 8                   Qatar             Switzerland        21.2
8        Match 9             Ivory Coast                 Ecuador        47.6
9       Match 10                 Germany                 Curaçao        78.6
10      Match 11             Netherlands                   Japan        62.0
11      Match 12                 Albania                 Tunisia        41.6
12      Match 13            Saudi Arabia                 Uruguay        23.6
13      Match 14                   Spain              Cabo Verde        77.5
14      Match 15                    Iran             New Zealand        75.2
15      Match 16                 Belgium                   Egypt        65.0
16      Match 17                  France                 Senegal        64.8
17      Match 18                 Bolivia                  Norway        30.8
18      Match 19               Argentina                 Algeria        69.8
19      Match 20                 Austria                  Jordan        71.0
20      Match 21                   Ghana                  Panama        27.1
21      Match 22                 England                 Croatia        60.6
22      Match 23                Portugal                DR Congo        71.0
23      Match 24              Uzbekistan                Colombia        18.3
24      Match 25          Czech Republic            South Africa        43.0
25      Match 26             Switzerland  Bosnia and Herzegovina        71.2
26      Match 27                  Canada                   Qatar        60.7
27      Match 28                  Mexico             South Korea        67.5
28      Match 29                  Brazil                   Haiti        82.9
29      Match 30                Scotland                 Morocco        27.5
30      Match 31                  Kosovo                Paraguay        35.4
31      Match 32           United States               Australia        61.9
32      Match 33                 Germany             Ivory Coast        64.6
33      Match 34                 Ecuador                 Curaçao        72.4
34      Match 35             Netherlands                 Albania        72.4
35      Match 36                 Tunisia                   Japan        22.6
36      Match 37                 Uruguay              Cabo Verde        70.1
37      Match 38                   Spain            Saudi Arabia        76.3
38      Match 39                 Belgium                    Iran        63.4
39      Match 40             New Zealand                   Egypt        11.6
40      Match 41                  Norway                 Senegal        51.3
41      Match 42                  France                 Bolivia        73.7
42      Match 43               Argentina                 Austria        68.3
43      Match 44                  Jordan                 Algeria        17.5
44      Match 45                 England                   Ghana        78.0
45      Match 46                  Panama                 Croatia        29.3
46      Match 47                Portugal              Uzbekistan        75.5
47      Match 48                Colombia                DR Congo        69.2
48      Match 49                Scotland                  Brazil        27.0
49      Match 50                 Morocco                   Haiti        82.4
50      Match 51             Switzerland                  Canada        61.7
51      Match 52  Bosnia and Herzegovina                   Qatar        34.2
52      Match 53          Czech Republic                  Mexico        25.3
53      Match 54            South Africa             South Korea        30.6
54      Match 55                 Curaçao             Ivory Coast        13.9
55      Match 56                 Ecuador                 Germany        45.6
56      Match 57                   Japan                 Albania        65.9
57      Match 58                 Tunisia             Netherlands        17.9
58      Match 59                  Kosovo           United States        26.4
59      Match 60                Paraguay               Australia        43.6
60      Match 61                  Norway                  France        34.4
61      Match 62                 Senegal                 Bolivia        65.5
62      Match 63                   Egypt                    Iran        51.1
63      Match 64             New Zealand                 Belgium         7.8
64      Match 65              Cabo Verde            Saudi Arabia        31.0
65      Match 66                 Uruguay                   Spain        39.3
66      Match 67                  Panama                 England        22.8
67      Match 68                 Croatia                   Ghana        73.7
68      Match 69                 Algeria                 Austria        48.9
69      Match 70                  Jordan               Argentina         7.5
70      Match 71                Colombia                Portugal        53.2
71      Match 72                DR Congo              Uzbekistan        51.9
72      Match 73      Group A runners-up      Group B runners-up        37.6
73      Match 74         Group E winners                 Group A        37.6
74      Match 75         Group F winners      Group C runners-up        37.6
75      Match 76         Group C winners      Group F runners-up        37.6
76      Match 77         Group I winners                 Group C        37.6
77      Match 78      Group E runners up      Group I runners-up        37.6
78      Match 79         Group A winners                 Group C        37.6
79      Match 80         Group L winners                 Group E        37.6
80      Match 81         Group D winners                 Group B        37.6
81      Match 82         Group G winners                 Group A        37.6
82      Match 83      Group K runners-up      Group L runners-up        37.6
83      Match 84         Group H winners      Group J runners-up        37.6
84      Match 85         Group B winners                 Group E        37.6
85      Match 86         Group J winners      Group H runners-up        37.6
86      Match 87         Group K winners                 Group D        37.6
87      Match 88      Group D runners-up      Group G runners-up        37.6
88      Match 89         Winner match 74         Winner match 77        37.6
89      Match 90         Winner match 73         Winner match 75        37.6
90      Match 91         Winner match 76         Winner match 78        37.6
91      Match 92         Winner match 79         Winner match 80        37.6
92      Match 93         Winner match 83         Winner match 84        37.6
93      Match 94         Winner match 81         Winner match 82        37.6
94      Match 95         Winner match 86         Winner match 88        37.6
95      Match 96         Winner match 85         Winner match 87        37.6
96      Match 97         Winner match 89         Winner match 90        37.6
97      Match 98         Winner match 93         Winner match 94        37.6
98      Match 99         Winner match 91         Winner match 92        37.6
99     Match 100         Winner match 95         Winner match 96        37.6
100    Match 101         Winner match 97         Winner match 98        37.6
101    Match 102         Winner match 99        Winner match 100        37.6
102    Match 103     Runner-up match 101     Runner-up match 102        37.6
103    Match 104        Winner match 101        Winner match 102        37.6

     Away Win %  Draw %
0          11.3    15.2
1          21.2    23.4
2          17.3    21.7
3          16.2    18.3
4          49.1    37.2
5          21.5    21.0
6          26.6    16.2
7          50.8    27.9
8          28.4    24.0
9           7.2    14.2
10         20.9    17.1
11         27.7    30.7
12         46.6    29.8
13          8.3    14.2
14          8.8    15.9
15         17.3    17.8
16         17.6    17.6
17         38.8    30.4
18         13.6    16.6
19         11.8    17.2
20         38.4    34.5
21         22.6    16.8
22         12.5    16.5
23         55.8    25.9
24         28.5    28.6
25         12.0    16.8
26         17.4    21.9
27         15.6    16.9
28          5.4    11.7
29         50.2    22.3
30         33.7    30.9
31         19.4    18.7
32         17.3    18.1
33         10.1    17.4
34         12.6    15.1
35         49.7    27.7
36         12.8    17.1
37          8.9    14.8
38         18.5    18.1
39         54.9    33.5
40         28.2    20.5
41         11.1    15.2
42         14.4    17.3
43         49.4    33.1
44          8.0    14.0
45         46.9    23.8
46          9.6    14.9
47         13.6    17.2
48         51.0    22.1
49          5.6    12.0
50         19.3    19.0
51         32.1    33.7
52         50.0    24.6
53         38.8    30.5
54         52.5    33.6
55         34.5    19.9
56         16.4    17.7
57         58.3    23.8
58         45.8    27.8
59         31.1    25.3
60         50.2    15.5
61         16.8    17.7
62         26.7    22.2
63         66.3    25.8
64         34.7    34.3
65         44.8    15.9
66         57.4    19.8
67         10.3    16.0
68         27.6    23.5
69         75.0    17.5
70         29.4    17.4
71         22.3    25.8
72         33.2    29.3
73         33.2    29.3
74         33.2    29.3
75         33.2    29.3
76         33.2    29.3
77         33.2    29.3
78         33.2    29.3
79         33.2    29.3
80         33.2    29.3
81         33.2    29.3
82         33.2    29.3
83         33.2    29.3
84         33.2    29.3
85         33.2    29.3
86         33.2    29.3
87         33.2    29.3
88         33.2    29.3
89         33.2    29.3
90         33.2    29.3
91         33.2    29.3
92         33.2    29.3
93         33.2    29.3
94         33.2    29.3
95         33.2    29.3
96         33.2    29.3
97         33.2    29.3
98         33.2    29.3
99         33.2    29.3
100        33.2    29.3
101        33.2    29.3
102        33.2    29.3
103        33.2    29.3

 Done! All match predictions saved to 'data/predictions_2026_output.csv'

In [73]:
# Save all matches to a new CSV file in your data folder
prediction_output.to_csv("data/predictions_2026_output.csv", index=False)
print("Successfully saved all predictions to data/predictions_2026_output.csv!")

Successfully saved all predictions to data/predictions_2026_output.csv!

In [72]:
import warnings
warnings.filterwarnings('ignore', category=UserWarning)

# 1. Predict probabilities using your 4-feature array
probs = model.predict_proba(X_future_array)

# 2. Map percentages
schedule["Home Win %"] = (probs[:, 0] * 100).round(1)
schedule["Away Win %"] = (probs[:, 1] * 100).round(1)
schedule["Draw %"] = (probs[:, 2] * 100).round(1)

# 3. Create the clean output dataframe
prediction_output = schedule[["match_number", "Home Team", "Away Team", "Home Win %", "Away Win %", "Draw %"]]

# --- NEW: Tell pandas to show ALL rows ---
import pandas as pd
pd.set_option('display.max_rows', None) 

# Print the entire table
print(prediction_output)

    match_number               Home Team               Away Team  Home Win %  \
0        Match 1                  Mexico            South Africa        73.5
1        Match 2             South Korea          Czech Republic        55.4
2        Match 3                  Canada  Bosnia and Herzegovina        61.0
3        Match 4           United States                Paraguay        65.5
4        Match 5                   Haiti                Scotland        13.7
5        Match 6               Australia                  Kosovo        57.6
6        Match 7                  Brazil                 Morocco        57.2
7        Match 8                   Qatar             Switzerland        21.2
8        Match 9             Ivory Coast                 Ecuador        47.6
9       Match 10                 Germany                 Curaçao        78.6
10      Match 11             Netherlands                   Japan        62.0
11      Match 12                 Albania                 Tunisia        41.6
12      Match 13            Saudi Arabia                 Uruguay        23.6
13      Match 14                   Spain              Cabo Verde        77.5
14      Match 15                    Iran             New Zealand        75.2
15      Match 16                 Belgium                   Egypt        65.0
16      Match 17                  France                 Senegal        64.8
17      Match 18                 Bolivia                  Norway        30.8
18      Match 19               Argentina                 Algeria        69.8
19      Match 20                 Austria                  Jordan        71.0
20      Match 21                   Ghana                  Panama        27.1
21      Match 22                 England                 Croatia        60.6
22      Match 23                Portugal                DR Congo        71.0
23      Match 24              Uzbekistan                Colombia        18.3
24      Match 25          Czech Republic            South Africa        43.0
25      Match 26             Switzerland  Bosnia and Herzegovina        71.2
26      Match 27                  Canada                   Qatar        60.7
27      Match 28                  Mexico             South Korea        67.5
28      Match 29                  Brazil                   Haiti        82.9
29      Match 30                Scotland                 Morocco        27.5
30      Match 31                  Kosovo                Paraguay        35.4
31      Match 32           United States               Australia        61.9
32      Match 33                 Germany             Ivory Coast        64.6
33      Match 34                 Ecuador                 Curaçao        72.4
34      Match 35             Netherlands                 Albania        72.4
35      Match 36                 Tunisia                   Japan        22.6
36      Match 37                 Uruguay              Cabo Verde        70.1
37      Match 38                   Spain            Saudi Arabia        76.3
38      Match 39                 Belgium                    Iran        63.4
39      Match 40             New Zealand                   Egypt        11.6
40      Match 41                  Norway                 Senegal        51.3
41      Match 42                  France                 Bolivia        73.7
42      Match 43               Argentina                 Austria        68.3
43      Match 44                  Jordan                 Algeria        17.5
44      Match 45                 England                   Ghana        78.0
45      Match 46                  Panama                 Croatia        29.3
46      Match 47                Portugal              Uzbekistan        75.5
47      Match 48                Colombia                DR Congo        69.2
48      Match 49                Scotland                  Brazil        27.0
49      Match 50                 Morocco                   Haiti        82.4
50      Match 51             Switzerland                  Canada        61.7
51      Match 52  Bosnia and Herzegovina                   Qatar        34.2
52      Match 53          Czech Republic                  Mexico        25.3
53      Match 54            South Africa             South Korea        30.6
54      Match 55                 Curaçao             Ivory Coast        13.9
55      Match 56                 Ecuador                 Germany        45.6
56      Match 57                   Japan                 Albania        65.9
57      Match 58                 Tunisia             Netherlands        17.9
58      Match 59                  Kosovo           United States        26.4
59      Match 60                Paraguay               Australia        43.6
60      Match 61                  Norway                  France        34.4
61      Match 62                 Senegal                 Bolivia        65.5
62      Match 63                   Egypt                    Iran        51.1
63      Match 64             New Zealand                 Belgium         7.8
64      Match 65              Cabo Verde            Saudi Arabia        31.0
65      Match 66                 Uruguay                   Spain        39.3
66      Match 67                  Panama                 England        22.8
67      Match 68                 Croatia                   Ghana        73.7
68      Match 69                 Algeria                 Austria        48.9
69      Match 70                  Jordan               Argentina         7.5
70      Match 71                Colombia                Portugal        53.2
71      Match 72                DR Congo              Uzbekistan        51.9
72      Match 73      Group A runners-up      Group B runners-up        37.6
73      Match 74         Group E winners                 Group A        37.6
74      Match 75         Group F winners      Group C runners-up        37.6
75      Match 76         Group C winners      Group F runners-up        37.6
76      Match 77         Group I winners                 Group C        37.6
77      Match 78      Group E runners up      Group I runners-up        37.6
78      Match 79         Group A winners                 Group C        37.6
79      Match 80         Group L winners                 Group E        37.6
80      Match 81         Group D winners                 Group B        37.6
81      Match 82         Group G winners                 Group A        37.6
82      Match 83      Group K runners-up      Group L runners-up        37.6
83      Match 84         Group H winners      Group J runners-up        37.6
84      Match 85         Group B winners                 Group E        37.6
85      Match 86         Group J winners      Group H runners-up        37.6
86      Match 87         Group K winners                 Group D        37.6
87      Match 88      Group D runners-up      Group G runners-up        37.6
88      Match 89         Winner match 74         Winner match 77        37.6
89      Match 90         Winner match 73         Winner match 75        37.6
90      Match 91         Winner match 76         Winner match 78        37.6
91      Match 92         Winner match 79         Winner match 80        37.6
92      Match 93         Winner match 83         Winner match 84        37.6
93      Match 94         Winner match 81         Winner match 82        37.6
94      Match 95         Winner match 86         Winner match 88        37.6
95      Match 96         Winner match 85         Winner match 87        37.6
96      Match 97         Winner match 89         Winner match 90        37.6
97      Match 98         Winner match 93         Winner match 94        37.6
98      Match 99         Winner match 91         Winner match 92        37.6
99     Match 100         Winner match 95         Winner match 96        37.6
100    Match 101         Winner match 97         Winner match 98        37.6
101    Match 102         Winner match 99        Winner match 100        37.6
102    Match 103     Runner-up match 101     Runner-up match 102        37.6
103    Match 104        Winner match 101        Winner match 102        37.6

     Away Win %  Draw %
0          11.3    15.2
1          21.2    23.4
2          17.3    21.7
3          16.2    18.3
4          49.1    37.2
5          21.5    21.0
6          26.6    16.2
7          50.8    27.9
8          28.4    24.0
9           7.2    14.2
10         20.9    17.1
11         27.7    30.7
12         46.6    29.8
13          8.3    14.2
14          8.8    15.9
15         17.3    17.8
16         17.6    17.6
17         38.8    30.4
18         13.6    16.6
19         11.8    17.2
20         38.4    34.5
21         22.6    16.8
22         12.5    16.5
23         55.8    25.9
24         28.5    28.6
25         12.0    16.8
26         17.4    21.9
27         15.6    16.9
28          5.4    11.7
29         50.2    22.3
30         33.7    30.9
31         19.4    18.7
32         17.3    18.1
33         10.1    17.4
34         12.6    15.1
35         49.7    27.7
36         12.8    17.1
37          8.9    14.8
38         18.5    18.1
39         54.9    33.5
40         28.2    20.5
41         11.1    15.2
42         14.4    17.3
43         49.4    33.1
44          8.0    14.0
45         46.9    23.8
46          9.6    14.9
47         13.6    17.2
48         51.0    22.1
49          5.6    12.0
50         19.3    19.0
51         32.1    33.7
52         50.0    24.6
53         38.8    30.5
54         52.5    33.6
55         34.5    19.9
56         16.4    17.7
57         58.3    23.8
58         45.8    27.8
59         31.1    25.3
60         50.2    15.5
61         16.8    17.7
62         26.7    22.2
63         66.3    25.8
64         34.7    34.3
65         44.8    15.9
66         57.4    19.8
67         10.3    16.0
68         27.6    23.5
69         75.0    17.5
70         29.4    17.4
71         22.3    25.8
72         33.2    29.3
73         33.2    29.3
74         33.2    29.3
75         33.2    29.3
76         33.2    29.3
77         33.2    29.3
78         33.2    29.3
79         33.2    29.3
80         33.2    29.3
81         33.2    29.3
82         33.2    29.3
83         33.2    29.3
84         33.2    29.3
85         33.2    29.3
86         33.2    29.3
87         33.2    29.3
88         33.2    29.3
89         33.2    29.3
90         33.2    29.3
91         33.2    29.3
92         33.2    29.3
93         33.2    29.3
94         33.2    29.3
95         33.2    29.3
96         33.2    29.3
97         33.2    29.3
98         33.2    29.3
99         33.2    29.3
100        33.2    29.3
101        33.2    29.3
102        33.2    29.3
103        33.2    29.3

In [71]:
import warnings
warnings.filterwarnings('ignore', category=UserWarning)

# Your prediction code below...
probs = model.predict_proba(X_future_array)

In [70]:
# 1. Pass the 4-feature matrix into your trained model
probs = model.predict_proba(X_future_array)

# 2. Assign the columns back to your schedule table
# Standard mapping used in your training: 0 = Home Win, 1 = Away Win, 2 = Draw
schedule["Home Win %"] = (probs[:, 0] * 100).round(1)
schedule["Away Win %"] = (probs[:, 1] * 100).round(1)
schedule["Draw %"] = (probs[:, 2] * 100).round(1)

# 3. Print your completed clean 2026 Prediction Table!
prediction_output = schedule[["match_number", "Home Team", "Away Team", "Home Win %", "Away Win %", "Draw %"]]
print(prediction_output.head(10))

  match_number      Home Team               Away Team  Home Win %  Away Win %  \
0      Match 1         Mexico            South Africa        73.5        11.3
1      Match 2    South Korea          Czech Republic        55.4        21.2
2      Match 3         Canada  Bosnia and Herzegovina        61.0        17.3
3      Match 4  United States                Paraguay        65.5        16.2
4      Match 5          Haiti                Scotland        13.7        49.1
5      Match 6      Australia                  Kosovo        57.6        21.5
6      Match 7         Brazil                 Morocco        57.2        26.6
7      Match 8          Qatar             Switzerland        21.2        50.8
8      Match 9    Ivory Coast                 Ecuador        47.6        28.4
9     Match 10        Germany                 Curaçao        78.6         7.2

   Draw %
0    15.2
1    23.4
2    21.7
3    18.3
4    37.2
5    21.0
6    16.2
7    27.9
8    24.0
9    14.2

c:\Users\rites\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [69]:
# 1. Create the Difference columns in the main schedule dataframe for your records
schedule["Rank Difference"] = schedule["Away Rank"] - schedule["Home Rank"]
schedule["Rating Difference"] = schedule["Home Rating"] - schedule["Away Rating"]

# 2. Extract EXACTLY the 4 baseline features that your model was fitted on
X_future = schedule[[
    "Home Rank", 
    "Away Rank", 
    "Home Rating", 
    "Away Rating"
]]

# 3. Convert to a raw matrix array to ensure flawless delivery
X_future_array = X_future.values

In [68]:
# Pass the raw numpy array to prevent any ValueError
probs = model.predict_proba(X_future_array)

# Standard mapping: 0 = Home Win, 1 = Away Win, 2 = Draw
schedule["Home Win %"] = (probs[:, 0] * 100).round(1)
schedule["Away Win %"] = (probs[:, 1] * 100).round(1)
schedule["Draw %"] = (probs[:, 2] * 100).round(1)

# Display your completed 2026 Prediction Table!
prediction_output = schedule[["match_number", "Home Team", "Away Team", "Home Win %", "Away Win %", "Draw %"]]
print(prediction_output.head(10))

c:\Users\rites\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

ValueError: X has 6 features, but LogisticRegression is expecting 4 features as input.

In [67]:
# Create the columns both ways just to be safe
schedule["Rank Difference"] = schedule["Away Rank"] - schedule["Home Rank"]
schedule["Rating Difference"] = schedule["Home Rating"] - schedule["Away Rating"]

schedule["Rank_Difference"] = schedule["Rank Difference"]
schedule["Rating_Difference"] = schedule["Rating Difference"]

# Extract exactly the 6 columns in the precise order your model expects
X_future = schedule[[
    "Home Rank", "Away Rank", "Home Rating", "Away Rating", 
    "Rank Difference", "Rating Difference"
]]

# Convert to a raw matrix to completely bypass Scikit-Learn's feature name check
X_future_array = X_future.values

In [66]:
# Create the columns both ways just to be safe
schedule["Rank Difference"] = schedule["Away Rank"] - schedule["Home Rank"]
schedule["Rating Difference"] = schedule["Home Rating"] - schedule["Away Rating"]

schedule["Rank_Difference"] = schedule["Rank Difference"]
schedule["Rating_Difference"] = schedule["Rating Difference"]

# Extract exactly the 6 columns in the precise order your model expects
X_future = schedule[[
    "Home Rank", "Away Rank", "Home Rating", "Away Rating", 
    "Rank Difference", "Rating Difference"
]]

# Convert to a raw matrix to completely bypass Scikit-Learn's feature name check
X_future_array = X_future.values

In [65]:
# Predict win/draw/loss distribution using your trained model
probs = model.predict_proba(X_future)

# Standard mapping: 0 = Home Win, 1 = Away Win, 2 = Draw
schedule["Home Win %"] = (probs[:, 0] * 100).round(1)
schedule["Away Win %"] = (probs[:, 1] * 100).round(1)
schedule["Draw %"] = (probs[:, 2] * 100).round(1)

# Review the finalized predictions output
prediction_output = schedule[["match_number", "Home Team", "Away Team", "Home Win %", "Away Win %", "Draw %"]]
print(prediction_output.head(10))

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Rank_Difference
- Rating_Difference

In [64]:
# Replicate training formulas exactly using underscores
schedule["Rank_Difference"] = schedule["Away Rank"] - schedule["Home Rank"]
schedule["Rating_Difference"] = schedule["Home Rating"] - schedule["Away Rating"]

# Select the feature array with matching column names
X_future = schedule[[
    "Home Rank", "Away Rank", "Home Rating", "Away Rating", 
    "Rank_Difference", "Rating_Difference"
]]

In [63]:
# Predict win/draw/loss distribution using your best model
# Classes mapping check: 0 = Home Win, 1 = Away Win, 2 = Draw
probs = model.predict_proba(X_future)

schedule["Home Win %"] = (probs[:, 0] * 100).round(1)
schedule["Away Win %"] = (probs[:, 1] * 100).round(1)
schedule["Draw %"] = (probs[:, 2] * 100).round(1)

# Review final outputs
prediction_output = schedule[["match_number", "Home Team", "Away Team", "Home Win %", "Away Win %", "Draw %"]]
print(prediction_output.head(10))

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Rank_Difference
- Rating_Difference

In [60]:
# Replicate training formulas exactly
schedule["Rank Difference"] = schedule["Away Rank"] - schedule["Home Rank"]
schedule["Rating Difference"] = schedule["Home Rating"] - schedule["Away Rating"]

# Select the feature array 
X_future = schedule[[
    "Home Rank", "Away Rank", "Home Rating", "Away Rating", 
    "Rank Difference", "Rating Difference"
]]

In [59]:
# Merge Home Team rankings
schedule = schedule.merge(
    ranking[["Country", "Rank", "Rating"]],
    left_on="Home Team",
    right_on="Country",
    how="left"
)
schedule.rename(columns={"Rank": "Home Rank", "Rating": "Home Rating"}, inplace=True)
schedule.drop(columns=["Country"], inplace=True)

# Merge Away Team rankings
schedule = schedule.merge(
    ranking[["Country", "Rank", "Rating"]],
    left_on="Away Team",
    right_on="Country",
    how="left"
)
schedule.rename(columns={"Rank": "Away Rank", "Rating": "Away Rating"}, inplace=True)
schedule.drop(columns=["Country"], inplace=True)

# Fill any missing placeholder rankings with a conservative average if necessary
schedule[["Home Rank", "Away Rank"]] = schedule[["Home Rank", "Away Rank"]].fillna(50)
schedule[["Home Rating", "Away Rating"]] = schedule[["Home Rating", "Away Rating"]].fillna(1500)

In [58]:
# Split combined team names on the ' v ' delimiter
schedule[['Home Team', 'Away Team']] = schedule['teams'].str.split(' v ', expand=True)

# Clean up long placeholder group names for non-determined teams if any remain
schedule['Home Team'] = schedule['Home Team'].str.split('/').str[0].str.strip()
schedule['Away Team'] = schedule['Away Team'].str.split('/').str[0].str.strip()

# Apply the same country map to the 2026 schedule to avoid merge issues
schedule["Home Team"] = schedule["Home Team"].replace(country_map)
schedule["Away Team"] = schedule["Away Team"].replace(country_map)

In [57]:
schedule.head()

,date,match_number,teams,group,stadium,date_dt
0,"Thursday, 11 June 2026",Match 1,Mexico v South Africa,Group A,Mexico City Stadium,2026-06-11
1,"Thursday, 11 June 2026",Match 2,Korea Republic v Czechia/Denmark/North Macedon...,Group A,Estadio Guadalajara,2026-06-11
2,"Friday, 12 June 2026",Match 3,Canada v Bosnia and Herzegovina/Italy/Northern...,Group B,Toronto Stadium,2026-06-12
3,"Friday, 12 June 2026",Match 4,USA v Paraguay,Group D,Los Angeles Stadium,2026-06-12
4,"Saturday, 13 June 2026",Match 5,Haiti v Scotland,Group C,Boston Stadium,2026-06-13

In [56]:
schedule.columns

Index(['date', 'match_number', 'teams', 'group', 'stadium', 'date_dt'], dtype='object')

In [55]:
print("Accuracy :", accuracy_score(y_test, rf_prediction))

print("Precision :", precision_score(y_test, rf_prediction, average="macro", zero_division=0))

print("Recall :", recall_score(y_test, rf_prediction, average="macro", zero_division=0))

print("F1 Score :", f1_score(y_test, rf_prediction, average="macro", zero_division=0))

Accuracy : 0.41304347826086957
Precision : 0.35141093474426804
Recall : 0.3680555555555556
F1 Score : 0.3569992099403865

In [54]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

rf_prediction = rf.predict(X_test)

In [53]:
print(X_train.columns)

Index(['Home Rank', 'Away Rank', 'Home Rating', 'Away Rating',
       'Rank Difference', 'Rating Difference'],
      dtype='object')

In [52]:
X_train = train[features]
X_test = test[features]

y_train = train["Result"]
y_test = test["Result"]

In [51]:
features = [
    "Home Rank",
    "Away Rank",
    "Home Rating",
    "Away Rating",
    "Rank Difference",
    "Rating Difference"
]

In [50]:
train = matches[matches["Year"] <= 2018]

test = matches[matches["Year"] == 2022]

In [49]:
X_train = train[features]

X_test = test[features]

KeyError: "['Rank Difference', 'Rating Difference'] not in index"

In [48]:
features = [
    "Home Rank",
    "Away Rank",
    "Home Rating",
    "Away Rating",
    "Rank Difference",
    "Rating Difference"
]

In [46]:
matches[[
    "Home Rank",
    "Away Rank",
    "Rank Difference",
    "Home Rating",
    "Away Rating",
    "Rating Difference"
]].head()

,Home Rank,Away Rank,Rank Difference,Home Rating,Away Rating,Rating Difference
0,2.0,9.0,7.0,1906.84,1736.01,170.83
1,15.0,10.0,-5.0,1677.17,1735.41,-58.24
4,1.0,2.0,1.0,1907.40,1906.84,0.56
7,15.0,37.0,22.0,1677.17,1520.59,156.58
10,1.0,9.0,8.0,1907.40,1736.01,171.39

In [45]:
matches["Rank Difference"] = matches["Away Rank"] - matches["Home Rank"]

matches["Rating Difference"] = matches["Home Rating"] - matches["Away Rating"]

In [44]:
print("Accuracy :", accuracy_score(y_test, prediction))

print("Precision :", precision_score(y_test, prediction, average="macro", zero_division=0))

print("Recall :", recall_score(y_test, prediction, average="macro", zero_division=0))

print("F1 Score :", f1_score(y_test, prediction, average="macro", zero_division=0))

Accuracy : 0.5869565217391305
Precision : 0.41141141141141135
Recall : 0.4166666666666667
F1 Score : 0.38950819672131143

In [43]:
print("Accuracy :", accuracy_score(y_test, prediction))

print("Precision :", precision_score(y_test, prediction, average="macro"))

print("Recall :", recall_score(y_test, prediction, average="macro"))

print("F1 Score :", f1_score(y_test, prediction, average="macro"))

Accuracy : 0.5869565217391305
Precision : 0.41141141141141135
Recall : 0.4166666666666667
F1 Score : 0.38950819672131143

c:\Users\rites\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [42]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

prediction = model.predict(X_test)

## Logistic Regression

In [41]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(374, 4)
(46, 4)
(374,)
(46,)

In [40]:
features = [
    "Home Rank",
    "Away Rank",
    "Home Rating",
    "Away Rating"
]

X_train = train[features]
X_test = test[features]

y_train = train["Result"]
y_test = test["Result"]

In [39]:
print("Training data:", train.shape)

print("Testing data:", test.shape)

Training data: (374, 42)
Testing data: (46, 42)

In [38]:
train = matches[matches["Year"] <= 2018]

test = matches[matches["Year"] == 2022]

In [37]:
sorted(matches["Year"].unique())

[np.int32(1930),
 np.int32(1934),
 np.int32(1938),
 np.int32(1950),
 np.int32(1954),
 np.int32(1958),
 np.int32(1962),
 np.int32(1966),
 np.int32(1970),
 np.int32(1974),
 np.int32(1978),
 np.int32(1982),
 np.int32(1986),
 np.int32(1990),
 np.int32(1994),
 np.int32(1998),
 np.int32(2002),
 np.int32(2006),
 np.int32(2010),
 np.int32(2014),
 np.int32(2018),
 np.int32(2022)]

In [36]:
matches[["Match Date", "Year"]].head()

   Match Date  Year
0   7/13/1930  1930
1   7/13/1930  1930
4   7/15/1930  1930
7   7/17/1930  1930
10  7/19/1930  1930

In [35]:
matches["Year"] = pd.to_datetime(matches["Match Date"]).dt.year

In [34]:
matches["Match Date"].head(10)

0     7/13/1930
1     7/13/1930
4     7/15/1930
7     7/17/1930
10    7/19/1930
12    7/20/1930
15    7/26/1930
17    7/30/1930
18    5/27/1934
20    5/27/1934
Name: Match Date, dtype: object

In [33]:
y.head()

0     0
1     0
4     0
7     0
10    0
Name: Result, dtype: int64

In [32]:
X.head()

    Home Rank  Away Rank  Home Rating  Away Rating
0         2.0        9.0      1906.84      1736.01
1        15.0       10.0      1677.17      1735.41
4         1.0        2.0      1907.40      1906.84
7        15.0       37.0      1677.17      1520.59
10        1.0        9.0      1907.40      1736.01

In [31]:
features = [
    "Home Rank",
    "Away Rank",
    "Home Rating",
    "Away Rating"
]

X = matches[features]

y = matches["Result"]

In [30]:
matches.columns

Index(['Key Id', 'Tournament Id', 'tournament Name', 'Match Id', 'Match Name',
       'Stage Name', 'Group Name', 'Group Stage', 'Knockout Stage', 'Replayed',
       'Replay', 'Match Date', 'Match Time', 'Stadium Id', 'Stadium Name',
       'City Name', 'Country Name', 'Home Team Id', 'Home Team Name',
       'Home Team Code', 'Away Team Id', 'Away Team Name', 'Away Team Code',
       'Score', 'Home Team Score', 'Away Team Score', 'Home Team Score Margin',
       'Away Team Score Margin', 'Extra Time', 'Penalty Shootout',
       'Score Penalties', 'Home Team Score Penalties',
       'Away Team Score Penalties', 'Result', 'Home Team Win', 'Away Team Win',
       'Draw', 'Home Rank', 'Home Rating', 'Away Rank', 'Away Rating'],
      dtype='object')

In [29]:
matches["Result"].value_counts()

Result
0    227
1    119
2     74
Name: count, dtype: int64

In [28]:
matches["Result"] = matches["Result"].replace({
    "home team win": 0,
    "away team win": 1,
    "draw": 2
})

matches["Result"] = matches["Result"].astype(int)

C:\Users\rites\AppData\Local\Temp\ipykernel_15812\1912086891.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  matches["Result"] = matches["Result"].replace({

In [27]:
matches["Result"].value_counts()

Result
home team win    227
away team win    119
draw              74
Name: count, dtype: int64

In [26]:
print(matches.shape)

(420, 41)

In [25]:
matches = matches.dropna(subset=["Home Rank", "Away Rank"])

In [24]:
print("Missing Home Rank:", matches["Home Rank"].isnull().sum())

print("Missing Away Rank:", matches["Away Rank"].isnull().sum())

Missing Home Rank: 316
Missing Away Rank: 339

In [23]:
matches[[
    "Home Team Name",
    "Home Rank",
    "Away Team Name",
    "Away Rank"
]].head(15)

   Home Team Name  Home Rank Away Team Name  Away Rank
0          France        2.0         Mexico        9.0
1   United States       15.0        Belgium       10.0
2      Yugoslavia        NaN         Brazil        5.0
3         Romania        NaN           Peru        NaN
4       Argentina        1.0         France        2.0
5           Chile        NaN         Mexico        9.0
6      Yugoslavia        NaN        Bolivia        NaN
7   United States       15.0       Paraguay       37.0
8         Uruguay       19.0           Peru        NaN
9           Chile        NaN         France        2.0
10      Argentina        1.0         Mexico        9.0
11         Brazil        5.0        Bolivia        NaN
12       Paraguay       37.0        Belgium       10.0
13        Uruguay       19.0        Romania        NaN
14      Argentina        1.0          Chile        NaN

In [22]:
matches = matches.merge(
    ranking[["Country", "Rank", "Rating"]],
    left_on="Away Team Name",
    right_on="Country",
    how="left"
)

matches.rename(columns={
    "Rank": "Away Rank",
    "Rating": "Away Rating"
}, inplace=True)

matches.drop(columns=["Country"], inplace=True)

In [21]:
matches = matches.merge(
    ranking[["Country", "Rank", "Rating"]],
    left_on="Home Team Name",
    right_on="Country",
    how="left"
)

matches.rename(columns={
    "Rank": "Home Rank",
    "Rating": "Home Rating"
}, inplace=True)

matches.drop(columns=["Country"], inplace=True)

In [20]:
country_map = {
    "USA": "United States",
    "IR Iran": "Iran",
    "Korea Republic": "South Korea",
    "Türkiye": "Turkey",
    "Côte d'Ivoire": "Ivory Coast",
    "Congo DR": "DR Congo",
    "Czechia": "Czech Republic"
}

ranking["Country"] = ranking["Country"].replace(country_map)

In [19]:
match_countries = set(matches["Home Team Name"]) | set(matches["Away Team Name"])
ranking_countries = set(ranking["Country"])

print("Countries in matches but not in rankings:")
print(sorted(match_countries - ranking_countries))

print("\nCountries in rankings but not in matches:")
print(sorted(ranking_countries - match_countries))

Countries in matches but not in rankings:
['Angola', 'Bolivia', 'Bulgaria', 'Cameroon', 'Chile', 'China', 'Costa Rica', 'Cuba', 'Czech Republic', 'Czechoslovakia', 'Denmark', 'Dutch East Indies', 'East Germany', 'El Salvador', 'Greece', 'Honduras', 'Hungary', 'Iceland', 'Iran', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Kuwait', 'Nigeria', 'North Korea', 'Northern Ireland', 'Peru', 'Poland', 'Republic of Ireland', 'Romania', 'Russia', 'Serbia', 'Serbia and Montenegro', 'Slovakia', 'Slovenia', 'South Korea', 'Soviet Union', 'Togo', 'Trinidad and Tobago', 'Turkey', 'Ukraine', 'United Arab Emirates', 'United States', 'Wales', 'West Germany', 'Yugoslavia', 'Zaire']

Countries in rankings but not in matches:
['Cabo Verde', 'Congo DR', 'Curaçao', 'Czechia', "Côte d'Ivoire", 'IR Iran', 'Jordan', 'Korea Republic', 'Türkiye', 'USA', 'Uzbekistan']

In [18]:
sorted(matches["Home Team Name"].unique())

['Algeria',
 'Angola',
 'Argentina',
 'Australia',
 'Austria',
 'Belgium',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Brazil',
 'Bulgaria',
 'Cameroon',
 'Canada',
 'Chile',
 'China',
 'Colombia',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Czech Republic',
 'Czechoslovakia',
 'Denmark',
 'East Germany',
 'Ecuador',
 'Egypt',
 'England',
 'France',
 'Germany',
 'Ghana',
 'Greece',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'Iran',
 'Iraq',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Mexico',
 'Morocco',
 'Netherlands',
 'New Zealand',
 'Nigeria',
 'North Korea',
 'Northern Ireland',
 'Norway',
 'Panama',
 'Paraguay',
 'Peru',
 'Poland',
 'Portugal',
 'Qatar',
 'Republic of Ireland',
 'Romania',
 'Russia',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Serbia and Montenegro',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'South Korea',
 'Soviet Union',
 'Spain',
 'Sweden',
 'Switzerland',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Ukraine',
 'United Arab Emirates',
 'United States',
 'Uruguay',
 'Wales',
 'West Germany',
 'Yugoslavia',
 'Zaire']

In [17]:
matches["Away Team Name"].unique()

array(['Mexico', 'Belgium', 'Brazil', 'Peru', 'France', 'Bolivia',
       'Paraguay', 'Romania', 'Chile', 'United States', 'Yugoslavia',
       'Argentina', 'Egypt', 'Netherlands', 'Hungary', 'Switzerland',
       'Sweden', 'Spain', 'Germany', 'Austria', 'Czechoslovakia',
       'Dutch East Indies', 'Norway', 'Poland', 'Cuba', 'Italy',
       'England', 'Scotland', 'South Korea', 'Turkey', 'West Germany',
       'Uruguay', 'Wales', 'Northern Ireland', 'Soviet Union', 'Colombia',
       'Bulgaria', 'North Korea', 'Portugal', 'Israel', 'El Salvador',
       'Morocco', 'Australia', 'Haiti', 'East Germany', 'Zaire', 'Iran',
       'Tunisia', 'Cameroon', 'New Zealand', 'Algeria', 'Honduras',
       'Kuwait', 'Iraq', 'Denmark', 'Canada', 'Republic of Ireland',
       'United Arab Emirates', 'Costa Rica', 'Russia', 'Saudi Arabia',
       'Greece', 'Nigeria', 'South Africa', 'Japan', 'Croatia', 'Jamaica',
       'Senegal', 'Slovenia', 'Ecuador', 'China', 'Ivory Coast',
       'Czech Republic', 'Ghana', 'Togo', 'Ukraine',
       'Trinidad and Tobago', 'Serbia and Montenegro', 'Angola',
       'Slovakia', 'Serbia', 'Bosnia and Herzegovina', 'Iceland',
       'Panama', 'Qatar'], dtype=object)

In [16]:
matches["Home Team Name"].unique()

array(['France', 'United States', 'Yugoslavia', 'Romania', 'Argentina',
       'Chile', 'Uruguay', 'Brazil', 'Paraguay', 'Austria',
       'Czechoslovakia', 'Germany', 'Hungary', 'Italy', 'Spain', 'Sweden',
       'Switzerland', 'Cuba', 'England', 'West Germany', 'Turkey',
       'Northern Ireland', 'Soviet Union', 'Mexico', 'Wales', 'Portugal',
       'North Korea', 'Peru', 'Belgium', 'Bulgaria', 'East Germany',
       'Zaire', 'Poland', 'Australia', 'Scotland', 'Netherlands', 'Haiti',
       'Tunisia', 'Algeria', 'Honduras', 'Canada', 'Morocco',
       'South Korea', 'Iraq', 'Denmark', 'United Arab Emirates',
       'Costa Rica', 'Cameroon', 'Republic of Ireland', 'Colombia',
       'Norway', 'Nigeria', 'Saudi Arabia', 'Bolivia', 'Russia', 'Greece',
       'Jamaica', 'South Africa', 'Japan', 'Croatia', 'China', 'Senegal',
       'Slovenia', 'Ecuador', 'Trinidad and Tobago',
       'Serbia and Montenegro', 'Angola', 'Czech Republic', 'Togo',
       'Iran', 'Ivory Coast', 'Ghana', 'Ukraine', 'Serbia', 'New Zealand',
       'Slovakia', 'Bosnia and Herzegovina', 'Egypt', 'Iceland', 'Panama',
       'Qatar'], dtype=object)

In [15]:
ranking.columns

Index(['Rank', 'Country', 'Rating'], dtype='object')

In [14]:
ranking.head()

   Rank    Country   Rating
0     1  Argentina  1907.40
1     2     France  1906.84
2     3      Spain  1879.58
3     4    England  1840.46
4     5     Brazil  1785.19

In [13]:
matches.isnull().sum()

Key Id                       0
Tournament Id                0
tournament Name              0
Match Id                     0
Match Name                   0
Stage Name                   0
Group Name                   0
Group Stage                  0
Knockout Stage               0
Replayed                     0
Replay                       0
Match Date                   0
Match Time                   0
Stadium Id                   0
Stadium Name                 0
City Name                    0
Country Name                 0
Home Team Id                 0
Home Team Name               0
Home Team Code               0
Away Team Id                 0
Away Team Name               0
Away Team Code               0
Score                        0
Home Team Score              0
Away Team Score              0
Home Team Score Margin       0
Away Team Score Margin       0
Extra Time                   0
Penalty Shootout             0
Score Penalties              0
Home Team Score Penalties    0
Away Team Score Penalties    0
Result                       0
Home Team Win                0
Away Team Win                0
Draw                         0
dtype: int64

In [12]:
matches.describe()

,Key Id,Group Stage,Knockout Stage,Replayed,Replay,Home Team Score,Away Team Score,Home Team Score Margin,Away Team Score Margin,Extra Time,Penalty Shootout,Home Team Score Penalties,Away Team Score Penalties,Home Team Win,Away Team Win,Draw
count,964.00000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000,964.000000
mean,482.50000,0.744813,0.255187,0.004149,0.004149,1.766598,1.054979,0.711618,-0.711618,0.075726,0.036307,0.121369,0.108921,0.565353,0.248963,0.185685
std,278.42713,0.436192,0.436192,0.064315,0.064315,1.601040,1.071720,1.925893,1.925893,0.264697,0.187150,0.665731,0.600764,0.495968,0.432637,0.389054
min,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-7.000000,-9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,241.75000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,482.50000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,723.25000,1.000000,1.000000,0.000000,0.000000,3.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,964.00000,1.000000,1.000000,1.000000,1.000000,10.000000,7.000000,9.000000,7.000000,1.000000,1.000000,5.000000,5.000000,1.000000,1.000000,1.000000

In [11]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Key Id                     964 non-null    int64
 1   Tournament Id              964 non-null    object
 2   tournament Name            964 non-null    object
 3   Match Id                   964 non-null    object
 4   Match Name                 964 non-null    object
 5   Stage Name                 964 non-null    object
 6   Group Name                 964 non-null    object
 7   Group Stage                964 non-null    int64
 8   Knockout Stage             964 non-null    int64
 9   Replayed                   964 non-null    int64
 10  Replay                     964 non-null    int64
 11  Match Date                 964 non-null    object
 12  Match Time                 964 non-null    object
 13  Stadium Id                 964 non-null    object
 14  Stadium Name               964 non-null    object
 15  City Name                  964 non-null    object
 16  Country Name               964 non-null    object
 17  Home Team Id               964 non-null    object
 18  Home Team Name             964 non-null    object
 19  Home Team Code             964 non-null    object
 20  Away Team Id               964 non-null    object
 21  Away Team Name             964 non-null    object
 22  Away Team Code             964 non-null    object
 23  Score                      964 non-null    object
 24  Home Team Score            964 non-null    int64
 25  Away Team Score            964 non-null    int64
 26  Home Team Score Margin     964 non-null    int64
 27  Away Team Score Margin     964 non-null    int64
 28  Extra Time                 964 non-null    int64
 29  Penalty Shootout           964 non-null    int64
 30  Score Penalties            964 non-null    object
 31  Home Team Score Penalties  964 non-null    int64
 32  Away Team Score Penalties  964 non-null    int64
 33  Result                     964 non-null    object
 34  Home Team Win              964 non-null    int64
 35  Away Team Win              964 non-null    int64
 36  Draw                       964 non-null    int64
dtypes: int64(16), object(21)
memory usage: 278.8+ KB

## Dataset Information

In [10]:
schedule.columns

Index(['date', 'match_number', 'teams', 'group', 'stadium', 'date_dt'], dtype='object')

In [9]:
ranking.columns

Index(['Rank', 'Country', 'Rating'], dtype='object')

In [8]:
matches.columns

Index(['Key Id', 'Tournament Id', 'tournament Name', 'Match Id', 'Match Name',
       'Stage Name', 'Group Name', 'Group Stage', 'Knockout Stage', 'Replayed',
       'Replay', 'Match Date', 'Match Time', 'Stadium Id', 'Stadium Name',
       'City Name', 'Country Name', 'Home Team Id', 'Home Team Name',
       'Home Team Code', 'Away Team Id', 'Away Team Name', 'Away Team Code',
       'Score', 'Home Team Score', 'Away Team Score', 'Home Team Score Margin',
       'Away Team Score Margin', 'Extra Time', 'Penalty Shootout',
       'Score Penalties', 'Home Team Score Penalties',
       'Away Team Score Penalties', 'Result', 'Home Team Win', 'Away Team Win',
       'Draw'],
      dtype='object')

In [7]:
schedule.head()

,date,match_number,teams,group,stadium,date_dt
0,"Thursday, 11 June 2026",Match 1,Mexico v South Africa,Group A,Mexico City Stadium,2026-06-11
1,"Thursday, 11 June 2026",Match 2,Korea Republic v Czechia/Denmark/North Macedon...,Group A,Estadio Guadalajara,2026-06-11
2,"Friday, 12 June 2026",Match 3,Canada v Bosnia and Herzegovina/Italy/Northern...,Group B,Toronto Stadium,2026-06-12
3,"Friday, 12 June 2026",Match 4,USA v Paraguay,Group D,Los Angeles Stadium,2026-06-12
4,"Saturday, 13 June 2026",Match 5,Haiti v Scotland,Group C,Boston Stadium,2026-06-13

In [6]:
ranking.head()

   Rank    Country   Rating
0     1  Argentina  1907.40
1     2     France  1906.84
2     3      Spain  1879.58
3     4    England  1840.46
4     5     Brazil  1785.19

In [5]:
matches.head()

,Key Id,Tournament Id,tournament Name,Match Id,Match Name,Stage Name,Group Name,Group Stage,Knockout Stage,Replayed,...,Away Team Score Margin,Extra Time,Penalty Shootout,Score Penalties,Home Team Score Penalties,Away Team Score Penalties,Result,Home Team Win,Away Team Win,Draw
0,1,WC-1930,1930 FIFA World Cup,M-1930-01,France v Mexico,group stage,Group 1,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
1,2,WC-1930,1930 FIFA World Cup,M-1930-02,United States v Belgium,group stage,Group 4,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
2,3,WC-1930,1930 FIFA World Cup,M-1930-03,Yugoslavia v Brazil,group stage,Group 2,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0
3,4,WC-1930,1930 FIFA World Cup,M-1930-04,Romania v Peru,group stage,Group 3,1,0,0,...,-2,0,0,0-0,0,0,home team win,1,0,0
4,5,WC-1930,1930 FIFA World Cup,M-1930-05,Argentina v France,group stage,Group 1,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0

In [4]:
matches = pd.read_csv(
    "data/FIFA World Cup 1930-2022 All Match Dataset.csv",
    encoding="cp1252"
)
ranking = pd.read_csv("data/fifa_rankings.csv")

schedule = pd.read_csv("data/schedule_2026.csv")

## Load Dataset

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import mean_absolute_error

# FIFA World Cup Prediction

## Round 2 - FIFA World Cup Prediction

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns